services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: development
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - gotenberg-proxy
      - sura
      - snippetserver

  gotenberg-proxy:
    restart: unless-stopped
    build:
      context: https://github.com/Simon-Dirks/gotenberg-proxy.git#main
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      GOTENBERG_HOST: http://gotenberg:3000
    depends_on:
      - gotenberg

  gotenberg:
    restart: unless-stopped
    image: gotenberg/gotenberg:8
    environment:
      - CHROMIUM_DISABLE_ROUTES=1

  sura:
    restart: unless-stopped
    build:
      context: https://github.com/Regionaal-Archief-Zuid-Utrecht/SURA.git#main
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - ./docker/sura/general.env:/app/general.env
      - ./docker/sura/jwt.env:/app/jwt.env

  snippetserver:
    restart: unless-stopped
    build:
      context: https://github.com/Regionaal-Archief-Zuid-Utrecht/snippetserver.git#main
    ports:
      - "127.0.0.1:8002:8000"
    environment:
      ALLOWED_HOSTS: opslag.razu.nl
      CORS_ALLOWED_ORIGINS: https://viewer.razu.nl,https://acceptatie.viewer.razu.nl,https://ontwikkel.viewer.razu.nl
