export const namespacePrefixes: Record<string, string> = {
  'https://schema.org/': 'sdo:',
  'http://schema.org/': 'sdo:',
  'http://www.w3.org/2004/02/skos/core#': 'skos:',
  'http://www.w3.org/1999/02/22-rdf-syntax-ns#': 'rdf:',
  'http://www.w3.org/2000/01/rdf-schema#': 'rdfs:',
  'http://www.w3.org/ns/shacl#': 'sh:',
  'http://xmlns.com/wot/0.1/': 'wot:',
  'http://www.w3.org/2002/07/owl#': 'owl:',
  'http://www.w3.org/2001/XMLSchema#': 'xsd:',
  'http://purl.org/dc/elements/1.1/': 'dc:',
  'http://purl.org/dc/terms/': 'dcterms:',
  'http://www.w3.org/1999/xhtml/vocab#': 'xhtml:',
  'http://www.w3.org/2003/06/sw-vocab-status/ns#': 'vs:',
  'http://purl.org/vocab/vann/': 'vann:',
  'http://web.resource.org/cc/': 'cc:',
  'http://www.w3.org/2003/01/geo/wgs84_pos#': 'geo:',
  'http://www.wikidata.org/entity/': 'wd:',
  'http://www.wikidata.org/prop/direct/': 'wdt:',
  'http://www.w3.org/ns/prov#': 'prov:',
  'https://w3id.org/pnv#': 'pnv:',
  'http://xmlns.com/foaf/0.1/': 'foaf:',
  'https://data.cbg.nl/pico#': 'pico:',
  'https://www.ica.org/standards/RiC/ontology#': 'rico:',
  'https://www.ica.org/standards/RiC/vocabularies/recordSetTypes#': 'ric-rst:',
  'https://data.cbg.nl/pico-terms#': 'picot:',
  'http://open.vocab.org/terms/': 'ov:',
};
