temp_pathname = /tmp

http.enabled = true
http.host = 0.0.0.0
http.port = 8182

endpoint.iiif.2.enabled = true
endpoint.iiif.3.enabled = true

source.static = S3Source
S3Source.endpoint = http://silo:9000
S3Source.region = us-east-1
S3Source.access_key_id = silo-admin
S3Source.secret_key = silo-demo-password
S3Source.lookup_strategy = ScriptLookupStrategy
S3Source.chunking.enabled = false
S3Source.chunking.cache.enabled = false

delegate_script.enabled = true
delegate_script.pathname = /etc/cantaloupe/delegates.rb

processor.selection_strategy = ManualSelectionStrategy
processor.ManualSelectionStrategy.jpg = TurboJpegProcessor
processor.ManualSelectionStrategy.fallback = Java2dProcessor

cache.client.enabled = false

print_stack_trace_on_error_pages = true
