import { FileType } from '../../models/file-type.model';
import { FileTypeConfig } from '../../models/settings/file-type-config.model';

export const fileTypeSettings: Record<FileType, FileTypeConfig> = {
  [FileType.IMAGE]: {
    extensions: [
      'jpg',
      'jpeg',
      'png',
      'gif',
      'bmp',
      'svg',
      'tiff',
      'tif',
      'webp',
    ],
    iconUrl: '/assets/img/file-types/image.png',
  },
  [FileType.PDF]: {
    extensions: ['pdf'],
    iconUrl: '/assets/img/file-types/pdf.png',
  },
  [FileType.DOC]: {
    extensions: [
      'doc',
      'docx',
      'docm',
      'dot',
      'dotx',
      'dotm',
      'odt',
      'rtf',
      'txt',
    ],
    iconUrl: '/assets/img/file-types/doc.png',
  },
  [FileType.XLS]: {
    extensions: [
      'xls',
      'xlsx',
      'xlsm',
      'xlsb',
      'xlt',
      'xltx',
      'xltm',
      'ods',
      'csv',
    ],
    iconUrl: '/assets/img/file-types/xls.png',
  },
  [FileType.PPT]: {
    extensions: ['ppt', 'pptx', 'pptm', 'pot', 'potx', 'potm', 'odp'],
    iconUrl: '/assets/img/file-types/ppt.png',
  },
  [FileType.OTHER_VIEWABLE_FILE]: {
    extensions: [
      '123',
      '602',
      'abw',
      'bib',
      'cdr',
      'cgm',
      'cmx',
      'cwk',
      'dbf',
      'dif',
      'dxf',
      'emf',
      'eps',
      'epub',
      'fodg',
      'fodp',
      'fods',
      'fodt',
      'fopd',
      'htm',
      'html',
      'hwp',
      'key',
      'ltx',
      'lwp',
      'mcw',
      'met',
      'mml',
      'mw',
      'numbers',
      'odd',
      'odg',
      'odm',
      'otg',
      'oth',
      'otp',
      'ots',
      'ott',
      'pages',
      'pbm',
      'pcd',
      'pct',
      'pcx',
      'pdb',
      'pgm',
      'ppm',
      'psd',
      'psw',
      'pub',
      'pwp',
      'pxl',
      'ras',
      'sda',
      'sdc',
      'sdd',
      'sdp',
      'sdw',
      'sgl',
      'slk',
      'smf',
      'stc',
      'std',
      'sti',
      'stw',
      'svm',
      'swf',
      'sxc',
      'sxd',
      'sxg',
      'sxi',
      'sxm',
      'sxw',
      'tga',
      'uof',
      'uop',
      'uos',
      'uot',
      'vdx',
      'vor',
      'vsd',
      'vsdm',
      'vsdx',
      'wb2',
      'wk1',
      'wks',
      'wmf',
      'wpd',
      'wpg',
      'wps',
      'xbm',
      'xhtml',
      'xlt',
      'xltm',
      'xltx',
      'xlw',
      'xml',
      'xpm',
      'zabw',
    ],
    iconUrl: '/assets/img/file-types/file.png',
  },
  [FileType.UNKNOWN]: {
    extensions: [],
    iconUrl: '/assets/img/file-types/file.png',
  },
};
