export const namespacePrefixes: Record<string, string> = {
  'https://www.ica.org/standards/RiC/ontology#': 'rico:',
  'https://schema.org/': 'sdo:',
  'http://www.w3.org/2004/02/skos/core#': 'skos:',
  'http://www.w3.org/1999/02/22-rdf-syntax-ns#': 'rdf:',
  'http://www.w3.org/2000/01/rdf-schema#': 'rdfs:',
  'http://www.wikidata.org/entity/': 'wd:',
  'http://www.wikidata.org/prop/direct/': 'wdt:',
  'http://www.w3.org/ns/prov#': 'prov:',
  'https://data.cbg.nl/pico#': 'pico:',
  'https://w3id.org/pnv#': 'pnv:',
  'http://xmlns.com/foaf/0.1/': 'foaf:',
  'https://data.razu.nl/def/ldto/': 'ldto:',
  'https://data.razu.nl/Kasteel-Amerongen/': 'ska:',
  'https://data.razu.nl/razu/': 'razu:',
  'https://www.ica.org/standards/RiC/vocabularies/recordSetTypes#': 'ric-rst:',
  'https://data.cbg.nl/pico-terms#': 'picot:',
  'http://www.nationaalarchief.nl/mdto-shacl#': 'mdto-sh:',
  'http://www.w3.org/ns/shacl#': 'sh:',
};
