// DaisyUI v5+ does not export a direct theme object for programmatic import. If you need a base theme, define it manually or ensure your workflow does not rely on this import.
// import daisyuiBase from 'daisyui/src/theming/themes';
// If you have a local copy or a recommended way to import base themes, update here.
// For now, remove this import to avoid build errors.
import { ThemeSettings } from '../models/settings/theme-settings.model';

export const developmentTheme: ThemeSettings = {
  primary: '#0082c2',
  'primary-content': '#ffffff',
  secondary: '#6d6d6d',
  'secondary-content': '#ffffff',
  accent: '#b3b3b3',
  'accent-content': '#000000',
  neutral: '#0082c2',
  'neutral-content': '#ffffff',
  'base-100': '#f2f2f2',
  'base-200': '#e5e4e2',
  'base-300': '#cccccc',
  'base-content': '#222222',
  background: '#f2f2f2',
  search_background: '#f2f2f2',
  '--rounded-box': '1rem',
  '--rounded-btn': '1rem',
  '--rounded-badge': '1rem',
  info: '#2094f3',
  'info-content': '#ffffff',
  success: '#009485',
  'success-content': '#ffffff',
  warning: '#ff9900',
  'warning-content': '#ffffff',
  error: '#ff5724',
  'error-content': '#ffffff',
};

export const acceptanceTheme: ThemeSettings = {
  primary: '#2e7d32',
  'primary-content': '#ffffff',
  secondary: '#388e3c',
  'secondary-content': '#ffffff',
  accent: '#a5d6a7',
  'accent-content': '#000000',
  neutral: '#66bb6a',
  'neutral-content': '#ffffff',
  'base-100': '#e8f5e9',
  'base-200': '#c8e6c9',
  'base-300': '#a5d6a7',
  'base-content': '#222222',
  background: '#e8f5e9',
  search_background: '#e8f5e9',
  '--rounded-box': '1rem',
  '--rounded-btn': '1rem',
  '--rounded-badge': '1rem',
  info: '#2094f3',
  'info-content': '#ffffff',
  success: '#009485',
  'success-content': '#ffffff',
  warning: '#ff9900',
  'warning-content': '#ffffff',
  error: '#ff5724',
  'error-content': '#ffffff',
};

export const productionTheme: ThemeSettings = {
  primary: '#6c5a82',
  'primary-content': '#ffffff',
  secondary: '#c2b280',
  'secondary-content': '#222222',
  accent: '#9ad199',
  'accent-content': '#222222',
  neutral: '#a999bd',
  'neutral-content': '#ffffff',
  'base-100': '#E5E4E2',
  'base-200': '#d6d1e0',
  'base-300': '#a999bd',
  'base-content': '#222222',
  background: '#E5E4E2',
  search_background: '#E5E4E2',
  '--rounded-box': '0.375rem',
  '--rounded-btn': '0.375rem',
  '--rounded-badge': '0.375rem',
  info: '#2094f3',
  'info-content': '#ffffff',
  success: '#009485',
  'success-content': '#ffffff',
  warning: '#ff9900',
  'warning-content': '#ffffff',
  error: '#ff5724',
  'error-content': '#ffffff',
};

export const testTheme: ThemeSettings = {
  primary: '#1565c0',
  'primary-content': '#ffffff',
  secondary: '#1976d2',
  'secondary-content': '#ffffff',
  accent: '#90caf9',
  'accent-content': '#000000',
  neutral: '#42a5f5',
  'neutral-content': '#ffffff',
  'base-100': '#e3f2fd',
  'base-200': '#bbdefb',
  'base-300': '#90caf9',
  'base-content': '#222222',
  background: '#e3f2fd',
  search_background: '#e3f2fd',
  '--rounded-box': '0.375rem',
  '--rounded-btn': '0.375rem',
  '--rounded-badge': '0.375rem',
  info: '#2094f3',
  'info-content': '#ffffff',
  success: '#009485',
  'success-content': '#ffffff',
  warning: '#ff9900',
  'warning-content': '#ffffff',
  error: '#ff5724',
  'error-content': '#ffffff',
};

